openapi: 3.0.0
info:
  title: Station Service API
  version: 1.0.0
  description: API for managing gas stations, including geospatial search.
servers:
  - url: http://localhost:8083
    description: Local Development Server
paths:
  /stations:
    get:
      summary: Get all stations
      operationId: getAllStations
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of stations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StationDto'
    post:
      summary: Create a new station
      operationId: createStation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStationDto'
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Station created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationDto'
  /stations/{id}:
    get:
      summary: Get station by ID
      operationId: getStationById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Station details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationDto'
        '404':
          description: Station not found
    put:
      summary: Update an existing station
      operationId: updateStation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStationDto'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Station updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationDto'
        '404':
          description: Station not found
    delete:
      summary: Delete a station by ID
      operationId: deleteStation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Station deleted successfully
        '404':
          description: Station not found
  /stations/nearby:
    get:
      summary: Find stations near a given geographical point
      operationId: getNearbyStations
      parameters:
        - name: latitude
          in: query
          required: true
          schema:
            type: number
            format: double
            minimum: -90
            maximum: 90
          description: Latitude of the center point
        - name: longitude
          in: query
          required: true
          schema:
            type: number
            format: double
            minimum: -180
            maximum: 180
          description: Longitude of the center point
        - name: distanceMeters
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 5000
            minimum: 100
            maximum: 50000
          description: Search radius in meters
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of nearby stations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StationDto'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    StationDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        location:
          type: object
          properties:
            latitude:
              type: number
              format: double
            longitude:
              type: number
              format: double
        status:
          type: string
          enum:
            - ACTIVA
            - INACTIVA
            - MANTENIMIENTO
    CreateStationDto:
      type: object
      required:
        - name
        - latitude
        - longitude
      properties:
        name:
          type: string
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
        status:
          type: string
          enum:
            - ACTIVA
            - INACTIVA
            - MANTENIMIENTO
          default: ACTIVA
    UpdateStationDto:
      type: object
      properties:
        name:
          type: string
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
        status:
          type: string
          enum:
            - ACTIVA
            - INACTIVA
            - MANTENIMIENTO
