# El archivo ahora tiene dos secciones principales: 'databases' y 'services'
databases:
  # Definición de la Base de Datos PostgreSQL
  - name: postgres-db-puntog
    databaseName: puntog
    user: puntog
    plan: free
    postgresMajorVersion: 16

  # Definición de la Caché de Redis
  - name: redis-cache-puntog
    plan: free
    ipAllowList: [] # Permite la conexión desde nuestros otros servicios

srvices:
  # Nuestro API Gateway (el único servicio público)
  - type: web
    name: api-gateway
    plan: free
    runtime: docker
    dockerfilePath: ./services/api-gateway/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: puntog-secrets
      - key: POSTGRES_HOST
        fromService:
          type: postgres
          name: postgres-db-puntog
          property: host
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache-puntog
          property: connectionString

  # El resto de microservicios (privados)
  - type: pserv
    name: auth-service
    plan: free
    runtime: docker
    dockerfilePath: ./services/auth-service/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: puntog-secrets
      - key: POSTGRES_HOST
        fromService:
          type: postgres
          name: postgres-db-puntog
          property: host
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache-puntog
          property: connectionString

  - type: pserv
    name: redemption-service
    plan: free
    runtime: docker
    dockerfilePath: ./services/redemption-service/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: puntog-secrets
      - key: POSTGRES_HOST
        fromService:
          type: postgres
          name: postgres-db-puntog
          property: host
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-cache-puntog
          property: connectionString

  - type: pserv
    name: ad-engine
    plan: free
    runtime: docker
    dockerfilePath: ./services/ad-engine/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: puntog-secrets
      - key: POSTGRES_HOST
        fromService:
          type: postgres
          name: postgres-db-puntog
          property: host

  - type: pserv
    name: raffle-service
    plan: free
    runtime: docker
    dockerfilePath: ./services/raffle-service/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: puntog-secrets
      - key: POSTGRES_HOST
        fromService:
          type: postgres
          name: postgres-db-puntog
          property: host