services:
  # Definición de la Base de Datos PostgreSQL como un servicio
  - type: pserv
    name: postgres-db-puntog
    plan: free
    postgres:
      databaseName: puntog
      user: puntog
      majorVersion: 16

  # Definición de la Caché de Redis como un servicio
  - type: pserv
    name: redis-cache-puntog
    plan: free
    redis: {} # Propiedad vacía para indicar que es un servicio de Redis

  # Nuestro API Gateway (público)
  - type: web
    name: api-gateway
    plan: free
    runtime: docker
    dockerfilePath: ./services/api-gateway/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: puntog-secrets
      - key: POSTGRES_URL # Render provee la URL de conexión completa
        fromService:
          type: pserv
          name: postgres-db-puntog
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: pserv
          name: redis-cache-puntog
          property: connectionString

  # El resto de microservicios (privados)
  - type: pserv
    name: auth-service
    plan: free
    runtime: docker
    dockerfilePath: ./services/auth-service/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: puntog-secrets
      - key: POSTGRES_URL
        fromService:
          type: pserv
          name: postgres-db-puntog
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: pserv
          name: redis-cache-puntog
          property: connectionString

  # (Añadir aquí las definiciones para redemption, ad-engine, y raffle siguiendo el mismo patrón de auth-service)
  - type: pserv
    name: redemption-service
    plan: free
    runtime: docker
    dockerfilePath: ./services/redemption-service/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: puntog-secrets
      - key: POSTGRES_URL
        fromService:
          type: pserv
          name: postgres-db-puntog
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: pserv
          name: redis-cache-puntog
          property: connectionString

  - type: pserv
    name: ad-engine
    plan: free
    runtime: docker
    dockerfilePath: ./services/ad-engine/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: puntog-secrets
      - key: POSTGRES_URL
        fromService:
          type: pserv
          name: postgres-db-puntog
          property: connectionString

  - type: pserv
    name: raffle-service
    plan: free
    runtime: docker
    dockerfilePath: ./services/raffle-service/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: puntog-secrets
      - key: POSTGRES_URL
        fromService:
          type: pserv
          name: postgres-db-puntog
          property: connectionString