services:
  # 1. La Base de Datos PostgreSQL
  - type: pserv
    name: postgres-db-puntog
    # El plan gratuito puede suspenderse por inactividad. Considera un plan de pago para producción.
    plan: free
    databaseName: puntog
    user: puntog
    postgresMajorVersion: 16

  # 2. La Caché de Redis
  - type: pserv
    name: redis-cache-puntog
    plan: free
    # Permite conexiones desde cualquier servicio dentro de tu cuenta de Render
    ipAllowList: []

  # 3. Nuestro API Gateway (el único servicio público con URL externa)
  - type: web
    name: api-gateway
    plan: free
    runtime: docker
    dockerfilePath: ./services/api-gateway/Dockerfile
    dockerContext: .
    envVars:
      # Usará un grupo de secretos centralizado que crearemos en Render
      - fromGroup: puntog-secrets
      # Render inyecta automáticamente las URLs de conexión a la DB y Redis
      - key: POSTGRES_HOST
        fromService:
          type: pserv
          name: postgres-db-puntog
          property: host
      - key: REDIS_URL
        fromService:
          type: pserv
          name: redis-cache-puntog
          property: connectionString

  # 4. El resto de microservicios (privados, solo accesibles a través del Gateway)
  - type: pserv
    name: auth-service
    plan: free
    runtime: docker
    dockerfilePath: ./services/auth-service/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: puntog-secrets
      - key: POSTGRES_HOST
        fromService:
          type: pserv
          name: postgres-db-puntog
          property: host
      - key: REDIS_URL
        fromService:
          type: pserv
          name: redis-cache-puntog
          property: connectionString

  - type: pserv
    name: redemption-service
    plan: free
    runtime: docker
    dockerfilePath: ./services/redemption-service/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: puntog-secrets
      - key: POSTGRES_HOST
        fromService:
          type: pserv
          name: postgres-db-puntog
          property: host
      - key: REDIS_URL
        fromService:
          type: pserv
          name: redis-cache-puntog
          property: connectionString

  - type: pserv
    name: ad-engine
    plan: free
    runtime: docker
    dockerfilePath: ./services/ad-engine/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: puntog-secrets
      - key: POSTGRES_HOST
        fromService:
          type: pserv
          name: postgres-db-puntog
          property: host

  - type: pserv
    name: raffle-service
    plan: free
    runtime: docker
    dockerfilePath: ./services/raffle-service/Dockerfile
    dockerContext: .
    envVars:
      - fromGroup: puntog-secrets
      - key: POSTGRES_HOST
        fromService:
          type: pserv
          name: postgres-db-puntog
          property: host