openapi: 3.0.0
info:
  title: Coupon Service API
  version: 1.0.0
  description: API for managing QR coupons.
servers:
  - url: http://localhost:8086
    description: Local Development Server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    GenerateQRRequest:
      type: object
      required:
        - stationId
        - employeeId
        - amount
      properties:
        stationId:
          type: string
          format: uuid
        employeeId:
          type: string
          format: uuid
        amount:
          type: integer
    GenerateQRResponse:
      type: object
      properties:
        couponId:
          type: string
          format: uuid
        qrCode:
          type: string
        token:
          type: string
        baseTickets:
          type: integer
        expiresAt:
          type: string
          format: date-time
    ScanQRRequest:
      type: object
      required:
        - qrCode
        - userId
      properties:
        qrCode:
          type: string
        userId:
          type: string
          format: uuid
    ScanQRResponse:
      type: object
      properties:
        couponId:
          type: string
          format: uuid
        token:
          type: string
        baseTickets:
          type: integer
        canActivate:
          type: boolean
        message:
          type: string
    ActivateCouponRequest:
      type: object
      required:
        - userId
      properties:
        userId:
          type: string
          format: uuid
    ActivateCouponResponse:
      type: object
      properties:
        couponId:
          type: string
          format: uuid
        token:
          type: string
        baseTickets:
          type: integer
        nextAdDuration:
          type: integer
        message:
          type: string
    CouponDetails:
      type: object
      properties:
        id:
          type: string
          format: uuid
        status:
          type: string
          enum: [GENERATED, SCANNED, ACTIVATED, EXPIRED]
        baseTickets:
          type: integer
        createdAt:
          type: string
          format: date-time
        expiresAt:
          type: string
          format: date-time

paths:
  /coupons:
    post:
      summary: Generate a new QR coupon
      operationId: generateCoupon
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateQRRequest'
      responses:
        '201':
          description: Coupon generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateQRResponse'

  /coupons/scan:
    post:
      summary: Scan a QR coupon to get its details for activation
      operationId: scanCoupon
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScanQRRequest'
      responses:
        '200':
          description: Coupon details retrieved for activation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScanQRResponse'

  /coupons/{id}:
    get:
      summary: Get coupon details by ID
      operationId: getCouponById
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Coupon details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CouponDetails'
        '404':
          description: Coupon not found

  /coupons/{id}/activation:
    post:
      summary: Activate a scanned coupon
      operationId: activateCoupon
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActivateCouponRequest'
      responses:
        '200':
          description: Coupon activated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivateCouponResponse'
        '409':
          description: Coupon already activated or in invalid state