openapi: 3.0.0
info:
  title: Ad Engine Service API
  version: 1.0.0
  description: API for ad selection, impression recording, and campaign management.
servers:
  - url: http://localhost:8084
    description: Local Development Server
paths:
  /ad/select:
    post:
      summary: Select an ad creative based on user and station context
      operationId: selectAd
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdSelectionRequest'
      responses:
        '200':
          description: Ad creative selected successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdCreativeResponse'
        '404':
          description: No active campaigns found for the given station
  /ad/impression:
    post:
      summary: Record an ad impression asynchronously
      operationId: recordImpression
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImpressionRequest'
      responses:
        '202':
          description: Impression recorded asynchronously
      security:
        - bearerAuth: []
  /ad/impressions:
    get:
      summary: Get a paginated list of ad impressions
      operationId: getImpressions
      parameters:
        - name: campaignId
          in: query
          required: false
          schema:
            type: integer
            format: int64
          description: Filter impressions by campaign ID
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
          description: Page number (0-indexed)
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 20
          description: Number of items per page
        - name: sort
          in: query
          required: false
          schema:
            type: string
          description: Sorting criteria in the format 'property(,asc|desc)'. Default sort order is ascending. Multiple sort criteria are supported.
      responses:
        '200':
          description: Paginated list of impressions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AdImpression'
      security:
        - bearerAuth: []
  /ad/impressions/count:
    get:
      summary: Get the total count of ad impressions
      operationId: countImpressions
      responses:
        '200':
          description: Total count of impressions
          content:
            application/json:
              schema:
                type: integer
                format: int64
      security:
        - bearerAuth: []
  /campaigns:
    get:
      summary: Get all campaigns for the authenticated advertiser
      operationId: getMyCampaigns
      responses:
        '200':
          description: List of campaigns
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CampaignDto'
      security:
        - bearerAuth: []
    post:
      summary: Create a new campaign
      operationId: createCampaign
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCampaignDto'
      responses:
        '201':
          description: Campaign created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignDto'
      security:
        - bearerAuth: []
  /campaigns/{id}:
    put:
      summary: Update an existing campaign
      operationId: updateCampaign
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: ID of the campaign to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCampaignDto' # Reusing CreateCampaignDto for update
      responses:
        '200':
          description: Campaign updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignDto'
        '404':
          description: Campaign not found
        '403':
          description: Forbidden - User does not own the campaign
      security:
        - bearerAuth: []
  /campaigns/summary:
    get:
      summary: Get performance summary for all campaigns of the authenticated advertiser
      operationId: getCampaignPerformanceSummary
      responses:
        '200':
          description: Campaign performance summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignPerformanceSummaryDto'
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    AdSelectionRequest:
      type: object
      required:
        - userId
        - stationId
        - sessionId
      properties:
        userId:
          type: string
          format: uuid
        stationId:
          type: integer
          format: int64
        sessionId:
          type: string
    AdCreativeResponse:
      type: object
      properties:
        adUrl:
          type: string
        campaignId:
          type: integer
          format: int64
        creativeId:
          type: string
    ImpressionRequest:
      type: object
      required:
        - userId
        - campaignId
        - creativeId
        - stationId
        - sessionId
        - duration
        - completed
        - skipped
      properties:
        userId:
          type: string
          format: uuid
        campaignId:
          type: integer
          format: int64
        creativeId:
          type: string
        stationId:
          type: integer
          format: int64
        sessionId:
          type: string
        sequenceId:
          type: integer
          format: int64
        duration:
          type: integer
          format: int64
        completed:
          type: boolean
        skipped:
          type: boolean
    AdImpression:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: string
          format: uuid
        campaignId:
          type: integer
          format: int64
        creativeId:
          type: string
        stationId:
          type: integer
          format: int64
        sessionId:
          type: string
        sequenceId:
          type: integer
          format: int64
        duration:
          type: integer
          format: int64
        completed:
          type: boolean
        skipped:
          type: boolean
        timestamp:
          type: string
          format: date-time
    CampaignDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        budget:
          type: number
          format: double
        adUrl:
          type: string
    CreateCampaignDto:
      type: object
      required:
        - name
        - startDate
        - endDate
        - budget
        - adUrl
      properties:
        name:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        budget:
          type: number
          format: double
        adUrl:
          type: string
    CampaignPerformanceSummaryDto:
      type: object
      properties:
        totalImpressions:
          type: integer
          format: int64
        totalBudgetSpent:
          type: number
          format: double
