name: CD to EKS

on:
  workflow_run:
    workflows: ["CI"] # Corrected workflow name
    types:
      - completed

env:
  AWS_REGION: us-east-1 # Replace with your desired AWS region
  EKS_CLUSTER_NAME: gasolinera-jsm-cluster # Replace with your EKS cluster name
  ECR_REPOSITORY: <YOUR_ECR_REPO_URL> # Replace with your ECR repository URL
  # Determine deployment environment based on the branch that triggered the CI workflow
  DEPLOY_ENV: ${{ github.event.workflow_run.head_branch == 'main' && 'production' || 'staging' }}

jobs:
  deploy-microservice:
    runs-on: ubuntu-latest
    needs: build # Ensure images are built before deploying
    if: "${{ github.event.workflow_run.conclusion == 'success' }}"
    permissions:
      id-token: write # This is required for aws-actions/configure-aws-credentials@v4
      contents: read # This is required for actions/checkout@v3
    strategy:
      matrix:
        service: [auth-service, redemption-service, ad-engine, raffle-service, api-gateway, station-service]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.GITHUB_ACTIONS_OIDC_ROLE }} # Replace with your OIDC role ARN
          aws-region: ${{ env.AWS_REGION }}

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.8.1' # Specify the Helm version

      - name: Lint Helm Chart for ${{ matrix.service }}
        run: helm lint ./infra/helm/gasolinera-jsm/charts/${{ matrix.service }}

      - name: Deploy ${{ matrix.service }}
        run: |
          helm upgrade --install ${{ matrix.service }} ./infra/helm/gasolinera-jsm/charts/${{ matrix.service }} \
            --set image.repository=${{ secrets.ECR_REPOSITORY }}/${{ matrix.service }}
            --set image.tag=${{ github.sha }}
            --namespace default # Or your desired namespace
            --set environment=${{ env.DEPLOY_ENV }} # Pass environment to Helm chart
